package org.infokiosk;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * This class was generated by Apache CXF 3.3.6
 * 2020-05-25T13:26:57.873+03:00
 * Generated source version: 3.3.6
 *
 */
@WebServiceClient(name = "Infokiosk",
                  wsdlLocation = "file:/C:/Users/127/AppData/Local/Temp/tempdir8385733799478294390.tmp/infokiosk_1.wsdl",
                  targetNamespace = "http://www.infokiosk.org")
public class InfokioskWS extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.infokiosk.org", "Infokiosk");
    public final static QName InfokioskSoap = new QName("http://www.infokiosk.org", "InfokioskSoap");
    public final static QName InfokioskSoap12 = new QName("http://www.infokiosk.org", "InfokioskSoap12");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/127/AppData/Local/Temp/tempdir8385733799478294390.tmp/infokiosk_1.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(InfokioskWS.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/127/AppData/Local/Temp/tempdir8385733799478294390.tmp/infokiosk_1.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public InfokioskWS(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public InfokioskWS(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public InfokioskWS() {
        super(WSDL_LOCATION, SERVICE);
    }

    public InfokioskWS(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public InfokioskWS(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public InfokioskWS(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     * 
     *       
     *
     * @return
     *     returns InfokioskPortType
     */
    @WebEndpoint(name = "InfokioskSoap")
    public InfokioskPortType getInfokioskSoap() {
        return super.getPort(InfokioskSoap, InfokioskPortType.class);
    }

    /**
     * 
     *       
     *
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns InfokioskPortType
     */
    @WebEndpoint(name = "InfokioskSoap")
    public InfokioskPortType getInfokioskSoap(WebServiceFeature... features) {
        return super.getPort(InfokioskSoap, InfokioskPortType.class, features);
    }


    /**
     *
     * @return
     *     returns InfokioskPortType
     */
    @WebEndpoint(name = "InfokioskSoap12")
    public InfokioskPortType getInfokioskSoap12() {
        return super.getPort(InfokioskSoap12, InfokioskPortType.class);
    }

    /**
     *
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns InfokioskPortType
     */
    @WebEndpoint(name = "InfokioskSoap12")
    public InfokioskPortType getInfokioskSoap12(WebServiceFeature... features) {
        return super.getPort(InfokioskSoap12, InfokioskPortType.class, features);
    }

}
