package org.infokiosk;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.6
 * 2020-05-31T21:14:35.925+03:00
 * Generated source version: 3.3.6
 *
 */
@WebService(targetNamespace = "http://www.infokiosk.org", name = "InfoKioskWSPortType") //NON-NLS NON-NLS
@XmlSeeAlso({org.infokiosk_types.ObjectFactory.class, ObjectFactory.class})
public interface InfoKioskWSPortType {

    @SuppressWarnings("UnnecessaryInterfaceModifier")
    @WebMethod(operationName = "GetCompanyName", action = "http://www.infokiosk.org#InfoKioskWS:GetCompanyName") //NON-NLS
    //NON-NLS NON-NLS
    @RequestWrapper(localName = "GetCompanyName", targetNamespace = "http://www.infokiosk.org", className = "org.infokiosk.GetCompanyName") //NON-NLS
    @ResponseWrapper(localName = "GetCompanyNameResponse", targetNamespace = "http://www.infokiosk.org", className = "org.infokiosk.GetCompanyNameResponse") //NON-NLS
    @WebResult(name = "return", targetNamespace = "http://www.infokiosk.org") //NON-NLS
    public java.lang.String getCompanyName()
;

    @SuppressWarnings("UnnecessaryInterfaceModifier")
    @WebMethod(operationName = "GetEmployeeData", action = "http://www.infokiosk.org#InfoKioskWS:GetEmployeeData") //NON-NLS
    @RequestWrapper(localName = "GetEmployeeData", targetNamespace = "http://www.infokiosk.org", className = "org.infokiosk.GetEmployeeData") //NON-NLS
    @ResponseWrapper(localName = "GetEmployeeDataResponse", targetNamespace = "http://www.infokiosk.org", className = "org.infokiosk.GetEmployeeDataResponse") //NON-NLS
    @WebResult(name = "return", targetNamespace = "http://www.infokiosk.org") //NON-NLS
    public org.infokiosk_types.EmployeeData getEmployeeData(

        @WebParam(name = "KeyCardNumber", targetNamespace = "http://www.infokiosk.org") //NON-NLS
        java.lang.String keyCardNumber
    );

    @SuppressWarnings("UnnecessaryInterfaceModifier")
    @WebMethod(operationName = "GetPaySlip", action = "http://www.infokiosk.org#InfoKioskWS:GetPaySlip") //NON-NLS
    @RequestWrapper(localName = "GetPaySlip", targetNamespace = "http://www.infokiosk.org", className = "org.infokiosk.GetPaySlip") //NON-NLS
    @ResponseWrapper(localName = "GetPaySlipResponse", targetNamespace = "http://www.infokiosk.org", className = "org.infokiosk.GetPaySlipResponse") //NON-NLS
    @WebResult(name = "return", targetNamespace = "http://www.infokiosk.org") //NON-NLS
    public byte[] getPaySlip(

        @WebParam(name = "IndividualId", targetNamespace = "http://www.infokiosk.org") //NON-NLS
        java.lang.String individualId,
        @WebParam(name = "Month", targetNamespace = "http://www.infokiosk.org") //NON-NLS
        javax.xml.datatype.XMLGregorianCalendar month,
        @WebParam(name = "FileType", targetNamespace = "http://www.infokiosk.org") //NON-NLS
        org.infokiosk_types.FileTypes fileType
    );
}
