package org.infokiosk;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.3.6
 * 2020-05-31T21:14:35.973+03:00
 * Generated source version: 3.3.6
 *
 */
@SuppressWarnings("unused")
@WebServiceClient(name = "InfoKioskWS",
                  wsdlLocation = "file:/C:/Users/127/AppData/Local/Temp/tempdir361428764797344436.tmp/infokiosk_1.wsdl",
                  targetNamespace = "http://www.infokiosk.org")
public class InfoKioskWS extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.infokiosk.org", "InfoKioskWS");
    public final static QName InfoKioskWSSoap = new QName("http://www.infokiosk.org", "InfoKioskWSSoap");
    public final static QName InfoKioskWSSoap12 = new QName("http://www.infokiosk.org", "InfoKioskWSSoap12");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/127/AppData/Local/Temp/tempdir361428764797344436.tmp/infokiosk_1.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(InfoKioskWS.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/127/AppData/Local/Temp/tempdir361428764797344436.tmp/infokiosk_1.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public InfoKioskWS(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public InfoKioskWS(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public InfoKioskWS() {
        super(WSDL_LOCATION, SERVICE);
    }

    public InfoKioskWS(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public InfoKioskWS(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public InfoKioskWS(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     * 
     *       
     *
     * @return
     *     returns InfoKioskWSPortType
     */
    @WebEndpoint(name = "InfoKioskWSSoap")
    public InfoKioskWSPortType getInfoKioskWSSoap() {
        return super.getPort(InfoKioskWSSoap, InfoKioskWSPortType.class);
    }

    /**
     * 
     *       
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns InfoKioskWSPortType
     */
    @WebEndpoint(name = "InfoKioskWSSoap")
    public InfoKioskWSPortType getInfoKioskWSSoap(WebServiceFeature... features) {
        return super.getPort(InfoKioskWSSoap, InfoKioskWSPortType.class, features);
    }


    /**
     *
     * @return
     *     returns InfoKioskWSPortType
     */
    @WebEndpoint(name = "InfoKioskWSSoap12")
    public InfoKioskWSPortType getInfoKioskWSSoap12() {
        return super.getPort(InfoKioskWSSoap12, InfoKioskWSPortType.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns InfoKioskWSPortType
     */
    @WebEndpoint(name = "InfoKioskWSSoap12")
    public InfoKioskWSPortType getInfoKioskWSSoap12(WebServiceFeature... features) {
        return super.getPort(InfoKioskWSSoap12, InfoKioskWSPortType.class, features);
    }

}
